# Generated by Django 3.2.9 on 2022-02-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255, null=True)),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], default='Breakfast', max_length=60)),
                ('schedule_time', models.DateTimeField(null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eatee', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('calories', models.CharField(max_length=255, null=True)),
                ('fat', models.CharField(max_length=255, null=True)),
                ('sodium', models.CharField(max_length=255, null=True)),
                ('protein', models.CharField(max_length=255, null=True)),
                ('carbs', models.CharField(max_length=255, null=True)),
                ('fibre', models.CharField(max_length=255, null=True)),
                ('sugar', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eater', to='core.user')),
            ],
        ),
    ]
