# Generated by Django 3.2.9 on 2022-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220218_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='accompaniment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
