# Generated by Django 3.2.9 on 2022-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_food_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
